export const TOPICS_LIST = [
  "Fiscal and Monetary Policy",
  "Tax Policy",
  "Health",
  "Education",
  "Well-Being",
  "Work and Pensions",
  "Business",
  "Economic Development",
  "Agricultural and Natural Resource Policy",
  "Environmental Policy",
  "Housing and Planning Policy",
  "Transportation Policy",
  "Trade",
  "Arts and Culture",
  "National Security",
  "Technology and Innovation",
  "Immigration",
  "Law",
];

export const reasonMap = {
  engagement: {
    reason_why_not_read_1: "Can't access journal articles",
    reason_why_not_read_2: "Don't know where to find",
    reason_why_not_read_3: "Too technical",
    reason_why_not_read_4: "Not relevant",
    reason_why_not_read_5: "Not timely enough",
    reason_why_not_read_6: "Don't trust research",
    reason_why_not_read_7: "No time",
  },
  communication: {
    comm_approach_1: "5-6 page summary",
    comm_approach_2: "1-2 page written summary",
    comm_approach_3: "1-2 page visual summary",
    comm_approach_4: "Slide deck",
    comm_approach_5: "2-sentence summary",
    comm_approach_6: "2-sentence policy recommendation",
    comm_approach_7: "Academic journal article",
  },
  usefulEcon: {
    useful_econ_law: "Law",
    useful_econ_immig: "Immigration",
    useful_econ_tech: "Technology and Innovation",
    useful_econ_secutity: "National Security",
    useful_econ_arts: "Arts and Culture",
    useful_econ_trade: "Trade",
    useful_econ_transp: "Transportation Policy",
    useful_econ_housing: "Housing and Planning Policy",
    useful_econ_environ: "Environmental Policy",
    useful_econ_agricul: "Agriculture and Natural Resources ",
    useful_econ_develop: "Economic Development",
    useful_econ_idustria: "Business",
    useful_econ_labor: "Work and Pensions",
    useful_econ_wellb: "Well-Being",
    useful_econ_educat: "Education",
    useful_econ_health: "Health",
    useful_econ_tax: "Tax Policy",
    useful_econ_fiscal: "Fiscal and Tax Policy",
  },
};
